#pragma config(Sensor, in1,    goalRetainerPot, sensorPotentiometer)
#pragma config(Sensor, in7,    hoistPot,       sensorPotentiometer)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  liftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  hoistQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  mobileGoalDetector, sensorSONAR_raw)
#pragma config(Sensor, dgtl7,  liftBump,       sensorTouch)
#pragma config(Sensor, dgtl8,  hoistLimit,     sensorTouch)
#pragma config(Motor,  port1,           goalRetainer,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftHoist,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightHoist,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

//--------------------------------------------------------------------//

void resetRobot()
{
	//Release goal retainer
	while(SensorValue[goalRetainerPot] > 0)
	{
		motor[goalRetainer] = -127;
	}
	motor[goalRetainer] = 0;

	//Reset mobile goal lift
  while(SensorValue[liftBump] == 0)
  {
  	motor[leftLift] = 96;
		motor[rightLift] = -96;
  }
  motor[leftLift] = 0;
	motor[rightLift] = 0;

	//Reset hoist limit
  while(SensorValue[hoistLimit] == 0)
  {
  	motor[leftHoist] = 8;
		motor[rightHoist] = -8;
  }
	wait1Msec(500);
	motor[leftHoist] = -24;
	motor[rightHoist] = 24;
	wait1Msec(750);
  motor[leftHoist] = 0;
	motor[rightHoist] = 0;

  wait1Msec(1000);
  SensorValue[liftQuad] = 0;
  SensorValue[hoistQuad] = 0;
}

void pre_auton()
{
  bStopTasksBetweenModes = true;
  bDisplayCompetitionStatusOnLcd = false;

  resetRobot();
}

//--------------------------------------------------------------------//

int deadZone(int inputVal, int deadZoneVal)
{
	if(fabs(inputVal) > deadZoneVal)
	{
		return inputVal;
	}
	else
	{
		return 0;
	}
}

void drive(int y, int r)
{
	motor[leftDrive] = y + r;
	motor[rightDrive] = -y + r;
}
void stopDriving()
{
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}
void gyroTurn(int target, float k_p)
{
	int pidSpeed;
	int error = 0;
	string debugString;
	while((-SensorValue[gyro] / 10.0) != target)
	{
		//Set error
		error = target - (-SensorValue[gyro] / 10.0);
		//Set pidSpeed using error and constants
		pidSpeed = k_p * error;
		//Max speed 64
		pidSpeed = (pidSpeed > 64) ? 64 : pidSpeed;
		drive(0, pidSpeed);

		sprintf(debugString, "%f", -SensorValue[gyro] / 10.0);
		displayLCDCenteredString(0, debugString);
	}
	stopDriving();
}

task liftHoist()
{
	//Raise hoist
	while(SensorValue[hoistQuad] < 80)
	{
		motor[leftHoist] = -127;
		motor[rightHoist] = 127;
	}
	motor[leftHoist] = -16;
	motor[rightHoist] = 16;

	return;
}

task lowerGoalLift()
{
	//Lower goal lift
	while(SensorValue[liftQuad] > -210)
	{
		motor[leftLift] = -96;
		motor[rightLift] = 96;
	}
	motor[leftLift] = 0;
	motor[rightLift] = 0;

	return;
}

task dropCone()
{
	//Lower hoist
	while(SensorValue[hoistQuad] > 60)
	{
		motor[leftHoist] = 64;
		motor[rightHoist] = -64;
	}
	motor[leftHoist] = -16;
	motor[rightHoist] = 16;

	//Open claw/drop cone
	motor[claw] = +127;
	wait1Msec(500);

	//Raise hoist
	while(SensorValue[hoistQuad] < 90)
	{
		motor[leftHoist] = -127;
		motor[rightHoist] = 127;
	}
	motor[leftHoist] = -16;
	motor[rightHoist] = 16;
	motor[claw] = 0;

	return;
}

task autonomous()
{
	//Reset gyro
	SensorValue[gyro] = 0;

	startTask(liftHoist);
	while(SensorValue[hoistQuad] < 20)
	{
		EndTimeSlice();
	}
	wait1Msec(250);
	startTask(lowerGoalLift);

	//Drive straight
	drive(32, 0);
	wait1Msec(100);
	drive(64, 0);
	wait1Msec(100);
	drive(127, 0);
	wait1Msec(2550);
	stopDriving();

	//Lift goal
	while(SensorValue[liftQuad] < -15)
	{
		motor[leftLift] = 127;
		motor[rightLift] = -127;
	}
	motor[leftLift] = 0;
	motor[rightLift] = 0;
	//Stop driving
	stopDriving();

	//Activate goal retainer
	while(SensorValue[goalRetainerPot] < 1600)
	{
		motor[goalRetainer] = 127;
	}
	motor[goalRetainer] = 20;

	//Pause
	wait1Msec(250);

	//Drive backward
	drive(-127, 0);

	startTask(dropCone);

	wait1Msec(2375);
	stopDriving();

	//Pause
	wait1Msec(250);

	//Turn around
	gyroTurn(135, 4.5);
	SensorValue[gyro] = 0;

	drive(127, 0);
	wait1Msec(750);
	stopDriving();
	gyroTurn(90, 4.5);


	//Drive straight into 10 point zone
	drive(127, 0);
	wait1Msec(1000);
	stopDriving();

	//Release goal retainer
	while(SensorValue[goalRetainerPot] > 1600)
	{
		motor[goalRetainer] = -127;
	}
	motor[goalRetainer] = 0;

	//Lower goal lift and hoist
	while(SensorValue[liftQuad] > -210)
	{
		//Goal lift
		motor[leftLift] = -96;
		motor[rightLift] = 96;

		//Hoist
		if(SensorValue[hoistQuad] > 80)
		{
			motor[leftHoist] = 16;
			motor[rightHoist] = -16;
		}
		else
		{
			motor[leftHoist] = 0;
			motor[rightHoist] = 0;
		}
	}
	motor[leftLift] = 0;
	motor[rightLift] = 0;

	//Drive backwards out of 10 point zone
	drive(-95 , 0);
	wait1Msec(500);
	stopDriving();
}

//--------------------------------------------------------------------//

task usercontrol()
{
	int y;
	int r;
	int liftSpeed;
	int hoistSpeed;
	bool mobileSideFront = true;
	bool mobileGoalDetectorEnabled = true;
	char lcdDebug[17];

  while(true)
	{
		//---------------------------- Drivetrain ----------------------------//

		if((vexRT[Btn7D] == 1)&&(vexRT[Btn8D] == 1))
		{
			while((vexRT[Btn7D] == 1)&&(vexRT[Btn8D] == 1))
			{
				EndTimeSlice();
			}
			mobileSideFront = !mobileSideFront;
		}
		y = mobileSideFront ? deadZone(vexRT[Ch3], 16) : -deadZone(vexRT[Ch3], 16);
		r = (vexRT[Btn5U] == 1) ? -64 : (vexRT[Btn6U] == 1) ? 64 : deadZone(vexRT[Ch1], 16) / 1.5;

		motor[leftDrive] = y + r;
		motor[rightDrive] = -y + r;

		//--------------------------------------------------------------------//



		//------------------------------- Hoist -------------------------------//

		hoistSpeed = deadZone(vexRT[Ch2Xmtr2], 16) / 2.5;

		if((vexRT[Btn7DXmtr2] == 1)&&(vexRT[Btn8DXmtr2] == 1))
		{
			while((vexRT[Btn7DXmtr2] == 1)&&(vexRT[Btn8DXmtr2] == 1))
			{
				EndTimeSlice();
			}
			mobileGoalDetectorEnabled = !mobileGoalDetectorEnabled;
		}

		if((mobileGoalDetectorEnabled)&&(SensorValue[mobileGoalDetector] > 1750))
		{
			if((hoistSpeed > 0)&&(SensorValue[hoistQuad] > 90))
			{
				hoistSpeed = 0;
			}
			else if((hoistSpeed < 0)&&(SensorValue[hoistQuad] <= 15))
			{
				hoistSpeed = 0;
			}
		}

		motor[leftHoist] = -hoistSpeed;
		motor[rightHoist] = hoistSpeed;

		//---------------------------------------------------------------------//



		//------------------------------- Lift -------------------------------//

		liftSpeed = deadZone(vexRT[Ch3Xmtr2], 16);
		if(((liftSpeed > 0)&&((SensorValue[liftQuad] >= -15)))|| \
			((liftSpeed < 0)&&(SensorValue[liftQuad] <= -210)))
		{
			liftSpeed = 0;
		}
		motor[leftLift] = liftSpeed;
		motor[rightLift] = -liftSpeed;

		if((SensorValue[goalRetainerPot] > 0)&&(vexRT[Btn7U] == 1))
		{
			motor[goalRetainerPot] = -127;
		}
		else if((SensorValue[goalRetainerPot] < 2000)&&(vexRT[Btn7D] == 1))
		{
			motor[goalRetainerPot] = 127;
		}
		else if(SensorValue[goalRetainerPot] > 1600)
		{
			motor[goalRetainer] = 20;
		}
		else
		{
			motor[goalRetainer] = 0;
		}

		//--------------------------------------------------------------------//



		//------------------------------- Claw -------------------------------//

		//If Button 5 up on the partner controller is pressed:
		if(vexRT[Btn5UXmtr2] == 1)
		{
			//Open claw
			motor[claw] = +64;
		}
		//Otherwise, if button 6 up on the partner controller is pressed:
		else if(vexRT[Btn6UXmtr2] == 1)
		{
			//Close claw
			motor[claw] = -64;
		}
		//Else:
		else
		{
			//Leave claw as it is
			motor[claw] = 0;
		}

		//--------------------------------------------------------------------//

		if((vexRT[Btn7R] == 1)&&(vexRT[Btn8L] == 1)&&(vexRT[Btn5D] == 1)&&(vexRT[Btn6D] == 1))
		{
			while((vexRT[Btn7R] == 1)&&(vexRT[Btn8L] == 1)&&(vexRT[Btn5D] == 1)&&(vexRT[Btn6D] == 1))
			{
				EndTimeSlice();
			}
			resetRobot();
		}

		sprintf(lcdDebug, "%d", SensorValue[goalRetainerPot]);
		displayLCDCenteredString(1, lcdDebug);
		wait1Msec(50);
	}
}
