#pragma config(Sensor, in7,    hoistPot,       sensorPotentiometer)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  liftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  hoistQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  mobileGoalDetector, sensorSONAR_raw)
#pragma config(Sensor, dgtl7,  liftBump,       sensorTouch)
#pragma config(Sensor, dgtl8,  hoistLimit,     sensorTouch)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftHoist,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightHoist,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

//--------------------------------------------------------------------//

void resetRobot()
{
  motor[claw] = -127;
  wait1Msec(1000);
  motor[claw] = 0;

  while(SensorValue[liftBump] == 0)
  {
  	motor[leftLift] = 96;
		motor[rightLift] = -96;
  }
  motor[leftLift] = 0;
	motor[rightLift] = 0;

	while((SensorValue[hoistLimit] == 0)&&(SensorValue[mobileGoalDetector] > 2000))
	{
		motor[leftHoist] = 48;
		motor[rightHoist] = -48;
	}
  while(SensorValue[hoistLimit] == 0)
  {
  	motor[leftHoist] = 8;
		motor[rightHoist] = -8;
  }
	wait1Msec(500);
	motor[leftHoist] = -24;
	motor[rightHoist] = 24;
	wait1Msec(750);
  motor[leftHoist] = 0;
	motor[rightHoist] = 0;

  wait1Msec(1000);
  SensorValue[liftQuad] = 0;
  SensorValue[hoistQuad] = 0;
}

void pre_auton()
{
  bStopTasksBetweenModes = true;
  bDisplayCompetitionStatusOnLcd = false;

  resetRobot();
}

//--------------------------------------------------------------------//

int deadZone(int inputVal, int deadZoneVal)
{
	if(fabs(inputVal) > deadZoneVal)
	{
		return inputVal;
	}
	else
	{
		return 0;
	}
}

void drive(int left, int right)
{
	motor[leftDrive] = -right;
	motor[rightDrive] = left;
}
void stopDriving()
{
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}

task autonomous()
{
	//Raise hoist
	while(SensorValue[hoistQuad] < 90)
	{
		motor[leftHoist] = -127;
		motor[rightHoist] = 127;
	}
	motor[leftHoist] = 0;
	motor[rightHoist] = 0;

	//Lower lift
	while(SensorValue[liftQuad] > -210)
	{
		motor[leftLift] = -96;
		motor[rightLift] = 96;
	}
	motor[leftLift] = 0;
	motor[rightLift] = 0;

	//Drive straight
	drive(127, 88);
	wait1Msec(2500);
	stopDriving();

	//Lift goal
	while(SensorValue[liftQuad] < -15)
	{
		motor[leftLift] = 127;
		motor[rightLift] = -127;
	}
	motor[leftLift] = 0;
	motor[rightLift] = 0;
	//Stop driving
	stopDriving();

	wait1Msec(500);
	drive(127, -127);
	wait1Msec(1000);
	stopDriving();
}

//--------------------------------------------------------------------//

task usercontrol()
{
	int y;
	int r;
	int liftSpeed;
	int hoistSpeed;
	bool mobileSideFront = true;
	bool mobileGoalDetectorEnabled = true;
	char lcdDebug[17];

  while(true)
	{
		//---------------------------- Drivetrain ----------------------------//

		if((vexRT[Btn7D] == 1)&&(vexRT[Btn8D] == 1))
		{
			while((vexRT[Btn7D] == 1)&&(vexRT[Btn8D] == 1))
			{
				EndTimeSlice();
			}
			mobileSideFront = !mobileSideFront;
		}
		y = mobileSideFront ? deadZone(vexRT[Ch3], 16) : -deadZone(vexRT[Ch3], 16);
		r = deadZone(vexRT[Ch4], 16) / 1.5;

		if((fabs(r) > 112)&&(r < 0))
		{
			r -= 36;
		}
		if((fabs(y) > 112)&&((y + r) > 0))
		{
			r += 30;
		}

		motor[leftDrive] = -y + r;
		motor[rightDrive] = y + r;

		//--------------------------------------------------------------------//



		//------------------------------- Hoist -------------------------------//

		hoistSpeed = deadZone(vexRT[Ch2Xmtr2], 16) / 2.5;
		displayLCDString(0, 0, "Unblocked");

		if((vexRT[Btn7DXmtr2] == 1)&&(vexRT[Btn8DXmtr2] == 1))
		{
			while((vexRT[Btn7DXmtr2] == 1)&&(vexRT[Btn8DXmtr2] == 1))
			{
				EndTimeSlice();
			}
			mobileGoalDetectorEnabled = !mobileGoalDetectorEnabled;
		}

		if((mobileGoalDetectorEnabled)&&(SensorValue[mobileGoalDetector] > 1750))
		{
			if((hoistSpeed > 0)&&(SensorValue[hoistQuad] > 90))
			{
				hoistSpeed = 0;
				displayLCDString(0, 0, "Blocked");
			}
			else if((hoistSpeed < 0)&&(SensorValue[hoistQuad] <= 15))
			{
				hoistSpeed = 0;
				displayLCDString(0, 0, "Blocked");
			}
		}

		motor[leftHoist] = -hoistSpeed;
		motor[rightHoist] = hoistSpeed;

		//---------------------------------------------------------------------//



		//------------------------------- Lift -------------------------------//

		liftSpeed = deadZone(vexRT[Ch3Xmtr2], 16);
		if(((liftSpeed > 0)&&((SensorValue[liftQuad] >= -15)))|| \
			((liftSpeed < 0)&&(SensorValue[liftQuad] <= -210)))
		{
			liftSpeed = 0;
		}
		motor[leftLift] = liftSpeed;
		motor[rightLift] = -liftSpeed;

		//--------------------------------------------------------------------//



		//------------------------------- Claw -------------------------------//

		//If Button 5 up on the partner controller is pressed:
		if(vexRT[Btn5UXmtr2] == 1)
		{
			//Open claw
			motor[claw] = +64;
		}
		//Otherwise, if button 6 up on the partner controller is pressed:
		else if(vexRT[Btn6UXmtr2] == 1)
		{
			//Close claw
			motor[claw] = -64;
		}
		//Else:
		else
		{
			//Leave claw as it is
			motor[claw] = 0;
		}

		//--------------------------------------------------------------------//

		sprintf(lcdDebug, "%d", SensorValue[hoistPot]);
		displayLCDCenteredString(1, lcdDebug);
		wait1Msec(50);
	}
}
