#pragma config(Sensor, dgtl1,  liftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  hoistQuad,      sensorQuadEncoder)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftHoist,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightHoist,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Initialize variables for loop
	int y;
	int r;

	//Reset encoders
	SensorValue[liftQuad] = 0;
	SensorValue[hoistQuad] = 0;

	while(true)
	{
		//---------------------------- Drivetrain ----------------------------//

		y = vexRT[Ch3];

		//If button 5 up is pressed:
		if(vexRT[Btn5U] == 1)
		{
			//Rotate left
			r = -64;
		}
		//Otherwise, if button 6 up is pressed:
		else if(vexRT[Btn6U] == 1)
		{
			//Rotate right
			r = +64;
		}
		//Else:
		else
		{
			//Don't rotate
			r = 0;
		}

		motor[leftDrive] = -y + r;
		motor[rightDrive] = y + r;

		//--------------------------------------------------------------------//



		//------------------------------- Hoist -------------------------------//

		motor[leftHoist] = -vexRT[Ch2Xmtr2];
		motor[rightHoist] = vexRT[Ch2Xmtr2];

		//---------------------------------------------------------------------//



		//------------------------------- Lift -------------------------------//

		if(((vexRT[Ch3Xmtr2] > 0)&&(SensorValue[liftQuad] <= 0))||
			((vexRT[Ch3Xmtr2] < 0)&&(SensorValue[liftQuad] >= -220)))
		{
			motor[leftLift] = vexRT[Ch3Xmtr2]; //Partner, right joystick up-down
			motor[rightLift] = -vexRT[Ch3Xmtr2]; //Partner, right joystick up-down
		}

		//--------------------------------------------------------------------//



		//------------------------------- Claw -------------------------------//

		//If Button 5 up on the partner controller is pressed:
		if(vexRT[Btn5UXmtr2] == 1)
		{
			//Open claw
			motor[claw] = +64;
		}
		//Otherwise, if button 6 up on the partner controller is pressed:
		else if(vexRT[Btn6UXmtr2] == 1)
		{
			//Close claw
			motor[claw] = -64;
		}
		//Else:
		else
		{
			//Leave claw as it is
			motor[claw] = 0;
		}

		//--------------------------------------------------------------------//
	}
}
